# ===========================================================
# File: R/dimv_diagnostics.R
# DIMV Diagnostics Module
# Provides: feature relevance scoring, adaptive regularization
#           and convergence diagnostics utilities
# ===========================================================

utils::globalVariables(c("feature", "score"))

#' Feature Relevance Scoring for DIMV
#'
#' Computes a simple multivariate relevance score for each feature using
#' the mean absolute correlation with all other variables. Higher scores
#' indicate a stronger contribution to the covariance structure, making
#' the feature more informative for conditional imputation.
#'
#' @param X A numeric data frame or matrix.
#'
#' @return A data frame with:
#' \itemize{
#'   \item \code{feature}: feature/column name
#'   \item \code{score}: relevance score (higher = more important)
#' }
#'
#' @export
#' @importFrom stats cor
feature_select_score <- function(X) {
  X <- as.data.frame(lapply(X, as.numeric))
  cmat <- stats::cor(X, use = "pairwise.complete.obs")
  # Mean absolute correlation with all other columns
  scores <- apply(abs(cmat), 1, function(v) mean(v[-which.max(v)], na.rm = TRUE))
  data.frame(feature = names(scores), score = scores, row.names = NULL)
}


#' Plot Feature Relevance Scores
#'
#' Visualizes feature ranking generated by \code{feature_select_score()}.
#' This plot can help assess which variables are most influential for
#' DIMV conditional modeling.
#'
#' @param score_df A data frame output from \code{feature_select_score()}.
#'
#' @return A \code{ggplot} object for visualization.
#'
#' @export
#' @import ggplot2
plot_feature_selection <- function(score_df) {
  score_df$feature <- factor(score_df$feature, levels = score_df$feature[order(score_df$score)])
  
  ggplot2::ggplot(score_df, ggplot2::aes(x = feature, y = score)) +
    ggplot2::geom_col(fill = "#2C7BB6") +
    ggplot2::coord_flip() +
    ggplot2::labs(title = "DIMV Feature Relevance Score",
                  x = "Feature", y = "Relevance Score") +
    ggplot2::theme_minimal()
}


#' Adaptive Lambda Recommendation (Heuristic)
#'
#' Recommends a ridge penalty (\code{lambda}) based on the median
#' pairwise correlation between variables. Stronger correlation and
#' multicollinearity imply greater regularization is needed for numerical
#' stability during conditional regression.
#'
#' @param X A numeric data frame or matrix.
#'
#' @return A numeric recommended lambda value.
#'
#' @export
#' @importFrom stats cor median
adaptive_lambda <- function(X) {
  X <- as.data.frame(lapply(X, as.numeric))
  cmat <- abs(stats::cor(X, use = "pairwise.complete.obs"))
  upper_vals <- cmat[upper.tri(cmat)]
  med_cor <- stats::median(upper_vals, na.rm = TRUE)
  
  # 3-level heuristic for regularization strength
  if (med_cor > 0.75) return(5)
  if (med_cor > 0.50) return(2)
  if (med_cor > 0.30) return(1)
  return(0.5)
}


#' DIMV Convergence Diagnostics
#'
#' Provides a brief summary of convergence quality for a fitted
#' \code{dimv_imputer} model. Useful for quick sanity checks prior
#' to downstream analysis.
#'
#' @param imputer A \code{dimv_imputer} object fitted by \code{dimv_train()}.
#'
#' @return A list containing:
#' \itemize{
#'   \item \code{iterations}: total iterations used during training
#'   \item \code{lambda}: base lambda used in training
#'   \item \code{residual_variance_summary}: summary stats of fitted residual variances
#' }
#'
#' @export
dimv_convergence_diag <- function(imputer) {
  if (!inherits(imputer, "dimv_imputer"))
    stop("Requires a dimv_imputer object.")
  
  list(
    iterations = imputer$iters,
    lambda = imputer$lambda,
    residual_variance_summary = summary(imputer$resid_var)
  )
}


#' Print DIMV Convergence Diagnostics
#'
#' Pretty-print wrapper for \code{dimv_convergence_diag()} to provide a
#' clean console summary of model convergence and variance behaviour.
#'
#' @param imputer A \code{dimv_imputer} object.
#'
#' @export
print_dimv_diag <- function(imputer) {
  diag <- dimv_convergence_diag(imputer)
  cat("\n=== DIMV Diagnostics ===\n")
  cat("Iterations:", diag$iterations, "\n")
  cat("Lambda:", diag$lambda, "\n")
  cat("Residual variance summary:\n")
  print(diag$residual_variance_summary)
  cat("========================\n")
}
