# ===========================================
# File: R/report_generator.R
# ===========================================
# - show pooled SE and 95% CI

generate_report <- function(results,
                            out_file = "dimv_report.html",
                            dataset_name = "Experiment Dataset") {
  if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
  if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr")
  if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
  if (!requireNamespace("viridis", quietly = TRUE)) install.packages("viridis")
  
  requireNamespace(ggplot2)
  requireNamespace(dplyr)
  requireNamespace(knitr)
  requireNamespace(viridis)
  
  results <- as.data.frame(results)
  # add 95% CIs
  results <- results %>%
    mutate(pred_low = mse_pred - 1.96 * mse_pred_se,
           pred_high = mse_pred + 1.96 * mse_pred_se,
           shap_low = mse_shap - 1.96 * mse_shap_se,
           shap_high = mse_shap + 1.96 * mse_shap_se)
  
  summary_plot <- ggplot(results, aes(x = method, y = mse_shap, fill = mechanism)) +
    geom_bar(stat = "identity", position = position_dodge(width = 0.7)) +
    geom_errorbar(aes(ymin = shap_low, ymax = shap_high), position = position_dodge(width = 0.7), width = 0.3) +
    facet_wrap(~ rate, labeller = label_both) +
    theme_minimal(base_size = 13) +
    scale_fill_viridis(discrete = TRUE) +
    labs(title = paste0("Explainability Report — ", dataset_name),
         subtitle = "Pooled SHAP MSE (Rubin pooling) with 95% CI",
         y = "Pooled SHAP MSE", x = "Imputation Method")
  
  img_summary <- tempfile(fileext = ".png")
  ggsave(filename = img_summary, plot = summary_plot, width = 9, height = 5, dpi = 120)
  
  # create table html
  table_html <- knitr::kable(results %>% select(method, mechanism, rate, m, mse_pred, mse_pred_se, mse_shap, mse_shap_se),
                             format = "html", digits = 4)
  
  # build HTML
  html_content <- paste0(
    "<html><head><title>DIMV Explainability Report</title></head><body>",
    "<h2>Dataset: ", dataset_name, "</h2>",
    "<p><b>Generated:</b> ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "</p>",
    "<h3>Results (pooled, Rubin rules)</h3>",
    table_html,
    "<h3>Aggregate Visualization (Pooled SHAP MSE ± 95% CI)</h3>",
    "<img src='", img_summary, "' width='900'/>",
    "<p><i>Report automatically generated by dimvExplainRpaper</i></p>",
    "</body></html>"
  )
  
  writeLines(html_content, out_file)
  message("HTML report saved to: ", normalizePath(out_file))
}
